name: Deploy Dist folder
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Clone the repo
            uses: actions/checkout@v5
            # run: |
            #   echo "Cloning repo ${{ github.repository }}"
            #   echo "${{toJson(github)}}"
            #   git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git myfiles
            #   cd myfiles
            #   ls -la
          - name: Setup Node Js
            uses: actions/setup-node@v6
            with:
              node-version: 22
          - name: Print Node version
            run: node -v
          - name: Cache dependencies
            uses: actions/cache@v4
            id: cache
            with:
              path: ${{ steps.cache.outputs.dir }}
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          - name: Install Dependencies
            if: steps.cache.outputs.cache-hit != 'true'
            run: npm -y install
          - name: Run Tests
            run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: Get Code
            uses: actions/checkout@v5
          - name: Setup Node Js
            uses: actions/setup-node@v6
            with:
              node-version: 22
          - name: Print Node version
            run: node -v
          - name: Cache dependencies
            uses: actions/cache@v4
            id: cache
            with:
              path: ${{ steps.cache.outputs.dir }}
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          - name: Install Dependencies
            if: steps.cache.outputs.cache-hit != 'true'
            run: npm -y install
          - name: Build Application
            run: npm run build
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Deploy Dist
            run: echo "Deployment completed"